name: Frontend CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    # --- REGISTRY LOGIN ---
    - name: Log in to GitHub Container Registry
      if: github.ref == 'refs/heads/main' && !env.ACT
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # --- BUILD FRONTEND ---
    - name: Build Frontend Docker Image
      run: |
        VERSION="v1.0.${GITHUB_RUN_NUMBER}"
        docker build -t ghcr.io/andreigmx/devops-playground-frontend:${VERSION} \
                     -t ghcr.io/andreigmx/devops-playground-frontend:latest .

    # --- PUSH TO REGISTRY ---
    - name: Push Frontend to GHCR
      if: github.ref == 'refs/heads/main' && !env.ACT
      run: |
        VERSION="v1.0.${GITHUB_RUN_NUMBER}"
        docker push ghcr.io/andreigmx/devops-playground-frontend:${VERSION}
        docker push ghcr.io/andreigmx/devops-playground-frontend:latest